baseURL = 'http://localhost:1313/'
languageCode = 'es'
title = 'Mi página con Hugo'
theme = 'temaSeleccionado'

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/inicio/"
    weight = 1

  [[menu.main]]
    name = "Markdown"
    url = "/markdown/"
    weight = 2

  [[menu.main]]
    name = "Imagenes"
    url = "/imagenes/"
    weight = 3

  [[menu.main]]
    name = "Tv"
    url = "/tv/"
    weight = 4


  [[menu.main]]
    name = "Python"
    url = "/python/"
    weight = 5

 [[menu.main]]
    name = ""
    url = "/ojfgewogjewo/"
    weight = 6